/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article implements Serializable {

    private static final long serialVersionUID = 175909026;

    private Integer   id;
    private String    author;
    private String    title;
    private Timestamp timeStamp;
    private String    content;

    public Article() {}

    public Article(Article value) {
        this.id = value.id;
        this.author = value.author;
        this.title = value.title;
        this.timeStamp = value.timeStamp;
        this.content = value.content;
    }

    public Article(
        Integer   id,
        String    author,
        String    title,
        Timestamp timeStamp,
        String    content
    ) {
        this.id = id;
        this.author = author;
        this.title = title;
        this.timeStamp = timeStamp;
        this.content = content;
    }

    @NotNull
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Size(max = 255)
    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Size(max = 1000)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Timestamp getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Timestamp timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Size(max = 16777215)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(id);
        sb.append(", ").append(author);
        sb.append(", ").append(title);
        sb.append(", ").append(timeStamp);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
