/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment implements Serializable {

    private static final long serialVersionUID = 1667406231;

    private UInteger  id;
    private UInteger  userId;
    private UInteger  articleId;
    private Timestamp timeStamp;
    private String    content;

    public Comment() {}

    public Comment(Comment value) {
        this.id = value.id;
        this.userId = value.userId;
        this.articleId = value.articleId;
        this.timeStamp = value.timeStamp;
        this.content = value.content;
    }

    public Comment(
        UInteger  id,
        UInteger  userId,
        UInteger  articleId,
        Timestamp timeStamp,
        String    content
    ) {
        this.id = id;
        this.userId = userId;
        this.articleId = articleId;
        this.timeStamp = timeStamp;
        this.content = content;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public UInteger getUserId() {
        return this.userId;
    }

    public void setUserId(UInteger userId) {
        this.userId = userId;
    }

    public UInteger getArticleId() {
        return this.articleId;
    }

    public void setArticleId(UInteger articleId) {
        this.articleId = articleId;
    }

    public Timestamp getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Timestamp timeStamp) {
        this.timeStamp = timeStamp;
    }

    @Size(max = 65535)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comment (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(articleId);
        sb.append(", ").append(timeStamp);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
