/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiseaseArticle implements Serializable {

    private static final long serialVersionUID = -1347187692;

    private Integer diseaseId;
    private Integer articleId;

    public DiseaseArticle() {}

    public DiseaseArticle(DiseaseArticle value) {
        this.diseaseId = value.diseaseId;
        this.articleId = value.articleId;
    }

    public DiseaseArticle(
        Integer diseaseId,
        Integer articleId
    ) {
        this.diseaseId = diseaseId;
        this.articleId = articleId;
    }

    public Integer getDiseaseId() {
        return this.diseaseId;
    }

    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }

    public Integer getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DiseaseArticle (");

        sb.append(diseaseId);
        sb.append(", ").append(articleId);

        sb.append(")");
        return sb.toString();
    }
}
