/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiseaseArticle implements Serializable {

    private static final long serialVersionUID = -2048567677;

    private UInteger diseaseId;
    private UInteger articleId;

    public DiseaseArticle() {}

    public DiseaseArticle(DiseaseArticle value) {
        this.diseaseId = value.diseaseId;
        this.articleId = value.articleId;
    }

    public DiseaseArticle(
        UInteger diseaseId,
        UInteger articleId
    ) {
        this.diseaseId = diseaseId;
        this.articleId = articleId;
    }

    public UInteger getDiseaseId() {
        return this.diseaseId;
    }

    public void setDiseaseId(UInteger diseaseId) {
        this.diseaseId = diseaseId;
    }

    public UInteger getArticleId() {
        return this.articleId;
    }

    public void setArticleId(UInteger articleId) {
        this.articleId = articleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DiseaseArticle (");

        sb.append(diseaseId);
        sb.append(", ").append(articleId);

        sb.append(")");
        return sb.toString();
    }
}
