/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiseaseSymptom implements Serializable {

    private static final long serialVersionUID = 1460526726;

    private Integer tagId;
    private Integer diseaseId;

    public DiseaseSymptom() {}

    public DiseaseSymptom(DiseaseSymptom value) {
        this.tagId = value.tagId;
        this.diseaseId = value.diseaseId;
    }

    public DiseaseSymptom(
        Integer tagId,
        Integer diseaseId
    ) {
        this.tagId = tagId;
        this.diseaseId = diseaseId;
    }

    public Integer getTagId() {
        return this.tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    public Integer getDiseaseId() {
        return this.diseaseId;
    }

    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DiseaseSymptom (");

        sb.append(tagId);
        sb.append(", ").append(diseaseId);

        sb.append(")");
        return sb.toString();
    }
}
