/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiseaseSymptom implements Serializable {

    private static final long serialVersionUID = 456800902;

    private Integer tagid;
    private Integer diseaseid;

    public DiseaseSymptom() {}

    public DiseaseSymptom(DiseaseSymptom value) {
        this.tagid = value.tagid;
        this.diseaseid = value.diseaseid;
    }

    public DiseaseSymptom(
        Integer tagid,
        Integer diseaseid
    ) {
        this.tagid = tagid;
        this.diseaseid = diseaseid;
    }

    public Integer getTagid() {
        return this.tagid;
    }

    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    public Integer getDiseaseid() {
        return this.diseaseid;
    }

    public void setDiseaseid(Integer diseaseid) {
        this.diseaseid = diseaseid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DiseaseSymptom (");

        sb.append(tagid);
        sb.append(", ").append(diseaseid);

        sb.append(")");
        return sb.toString();
    }
}
