/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFavouritearticle implements Serializable {

    private static final long serialVersionUID = 281381786;

    private UInteger userId;
    private UInteger articleId;

    public UserFavouritearticle() {}

    public UserFavouritearticle(UserFavouritearticle value) {
        this.userId = value.userId;
        this.articleId = value.articleId;
    }

    public UserFavouritearticle(
        UInteger userId,
        UInteger articleId
    ) {
        this.userId = userId;
        this.articleId = articleId;
    }

    public UInteger getUserId() {
        return this.userId;
    }

    public void setUserId(UInteger userId) {
        this.userId = userId;
    }

    public UInteger getArticleId() {
        return this.articleId;
    }

    public void setArticleId(UInteger articleId) {
        this.articleId = articleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserFavouritearticle (");

        sb.append(userId);
        sb.append(", ").append(articleId);

        sb.append(")");
        return sb.toString();
    }
}
