/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Disease;
import jooq.tables.Symptom;
import jooq.tables.records.DiseaseRecord;
import jooq.tables.records.SymptomRecord;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>webdoctor</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DiseaseRecord> KEY_DISEASE_PRIMARY = UniqueKeys0.KEY_DISEASE_PRIMARY;
    public static final UniqueKey<SymptomRecord> KEY_SYMPTOM_PRIMARY = UniqueKeys0.KEY_SYMPTOM_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DiseaseRecord> KEY_DISEASE_PRIMARY = createUniqueKey(Disease.DISEASE, "KEY_disease_PRIMARY", Disease.DISEASE.ID);
        public static final UniqueKey<SymptomRecord> KEY_SYMPTOM_PRIMARY = createUniqueKey(Symptom.SYMPTOM, "KEY_symptom_PRIMARY", Symptom.SYMPTOM.ID);
    }
}
