/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq;


import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import webdoctor.jooq.tables.Disease;
import webdoctor.jooq.tables.Symptom;
import webdoctor.jooq.tables.User;
import webdoctor.jooq.tables.records.DiseaseRecord;
import webdoctor.jooq.tables.records.SymptomRecord;
import webdoctor.jooq.tables.records.UserRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>webdoctor</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DiseaseRecord> KEY_DISEASE_PRIMARY = UniqueKeys0.KEY_DISEASE_PRIMARY;
    public static final UniqueKey<SymptomRecord> KEY_SYMPTOM_PRIMARY = UniqueKeys0.KEY_SYMPTOM_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DiseaseRecord> KEY_DISEASE_PRIMARY = createUniqueKey(Disease.DISEASE, "KEY_disease_PRIMARY", Disease.DISEASE.ID);
        public static final UniqueKey<SymptomRecord> KEY_SYMPTOM_PRIMARY = createUniqueKey(Symptom.SYMPTOM, "KEY_symptom_PRIMARY", Symptom.SYMPTOM.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }
}
