/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Disease;
import jooq.tables.Symptom;


/**
 * Convenience access to all tables in webdoctor
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>webdoctor.disease</code>.
     */
    public static final Disease DISEASE = jooq.tables.Disease.DISEASE;

    /**
     * The table <code>webdoctor.symptom</code>.
     */
    public static final Symptom SYMPTOM = jooq.tables.Symptom.SYMPTOM;
}
