/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq;


import javax.annotation.Generated;

import webdoctor.jooq.tables.Article;
import webdoctor.jooq.tables.Comment;
import webdoctor.jooq.tables.Disease;
import webdoctor.jooq.tables.DiseaseSymptom;
import webdoctor.jooq.tables.Symptom;
import webdoctor.jooq.tables.User;
import webdoctor.jooq.tables.UserFavouritearticle;


/**
 * Convenience access to all tables in webdoctor
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>webdoctor.article</code>.
     */
    public static final Article ARTICLE = webdoctor.jooq.tables.Article.ARTICLE;

    /**
     * The table <code>webdoctor.comment</code>.
     */
    public static final Comment COMMENT = webdoctor.jooq.tables.Comment.COMMENT;

    /**
     * The table <code>webdoctor.disease</code>.
     */
    public static final Disease DISEASE = webdoctor.jooq.tables.Disease.DISEASE;

    /**
     * The table <code>webdoctor.disease_symptom</code>.
     */
    public static final DiseaseSymptom DISEASE_SYMPTOM = webdoctor.jooq.tables.DiseaseSymptom.DISEASE_SYMPTOM;

    /**
     * The table <code>webdoctor.symptom</code>.
     */
    public static final Symptom SYMPTOM = webdoctor.jooq.tables.Symptom.SYMPTOM;

    /**
     * The table <code>webdoctor.user</code>.
     */
    public static final User USER = webdoctor.jooq.tables.User.USER;

    /**
     * The table <code>webdoctor.user_favouritearticle</code>.
     */
    public static final UserFavouritearticle USER_FAVOURITEARTICLE = webdoctor.jooq.tables.UserFavouritearticle.USER_FAVOURITEARTICLE;
}
