/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.Size;

import org.jooq.Field;
<<<<<<< HEAD
import org.jooq.Record4;
import org.jooq.Row4;
=======
import org.jooq.Record5;
import org.jooq.Row5;
>>>>>>> yibin
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;

import webdoctor.jooq.tables.Article;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
<<<<<<< HEAD
public class ArticleRecord extends TableRecordImpl<ArticleRecord> implements Record4<UInteger, String, Timestamp, String> {

    private static final long serialVersionUID = 512104837;
=======
public class ArticleRecord extends TableRecordImpl<ArticleRecord> implements Record5<UInteger, Integer, String, Timestamp, String> {

    private static final long serialVersionUID = -949240726;
>>>>>>> yibin

    /**
     * Setter for <code>webdoctor.article.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>webdoctor.article.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
<<<<<<< HEAD
     * Setter for <code>webdoctor.article.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
=======
     * Setter for <code>webdoctor.article.author_id</code>.
     */
    public void setAuthorId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>webdoctor.article.author_id</code>.
     */
    public Integer getAuthorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>webdoctor.article.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
>>>>>>> yibin
    }

    /**
     * Getter for <code>webdoctor.article.title</code>.
     */
    @Size(max = 1000)
    public String getTitle() {
<<<<<<< HEAD
        return (String) get(1);
=======
        return (String) get(2);
>>>>>>> yibin
    }

    /**
     * Setter for <code>webdoctor.article.time_stamp</code>.
     */
    public void setTimeStamp(Timestamp value) {
<<<<<<< HEAD
        set(2, value);
=======
        set(3, value);
>>>>>>> yibin
    }

    /**
     * Getter for <code>webdoctor.article.time_stamp</code>.
     */
    public Timestamp getTimeStamp() {
<<<<<<< HEAD
        return (Timestamp) get(2);
=======
        return (Timestamp) get(3);
>>>>>>> yibin
    }

    /**
     * Setter for <code>webdoctor.article.content</code>.
     */
    public void setContent(String value) {
<<<<<<< HEAD
        set(3, value);
=======
        set(4, value);
>>>>>>> yibin
    }

    /**
     * Getter for <code>webdoctor.article.content</code>.
     */
    @Size(max = 16777215)
    public String getContent() {
<<<<<<< HEAD
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
=======
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
>>>>>>> yibin
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public Row4<UInteger, String, Timestamp, String> fieldsRow() {
        return (Row4) super.fieldsRow();
=======
    public Row5<UInteger, Integer, String, Timestamp, String> fieldsRow() {
        return (Row5) super.fieldsRow();
>>>>>>> yibin
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public Row4<UInteger, String, Timestamp, String> valuesRow() {
        return (Row4) super.valuesRow();
=======
    public Row5<UInteger, Integer, String, Timestamp, String> valuesRow() {
        return (Row5) super.valuesRow();
>>>>>>> yibin
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Article.ARTICLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public Field<String> field2() {
=======
    public Field<Integer> field2() {
        return Article.ARTICLE.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
>>>>>>> yibin
        return Article.ARTICLE.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public Field<Timestamp> field3() {
=======
    public Field<Timestamp> field4() {
>>>>>>> yibin
        return Article.ARTICLE.TIME_STAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public Field<String> field4() {
=======
    public Field<String> field5() {
>>>>>>> yibin
        return Article.ARTICLE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public String value2() {
=======
    public Integer value2() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
>>>>>>> yibin
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public Timestamp value3() {
=======
    public Timestamp value4() {
>>>>>>> yibin
        return getTimeStamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public String value4() {
=======
    public String value5() {
>>>>>>> yibin
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public ArticleRecord value2(String value) {
=======
    public ArticleRecord value2(Integer value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value3(String value) {
>>>>>>> yibin
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public ArticleRecord value3(Timestamp value) {
=======
    public ArticleRecord value4(Timestamp value) {
>>>>>>> yibin
        setTimeStamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public ArticleRecord value4(String value) {
=======
    public ArticleRecord value5(String value) {
>>>>>>> yibin
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
<<<<<<< HEAD
    public ArticleRecord values(UInteger value1, String value2, Timestamp value3, String value4) {
=======
    public ArticleRecord values(UInteger value1, Integer value2, String value3, Timestamp value4, String value5) {
>>>>>>> yibin
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
<<<<<<< HEAD
=======
        value5(value5);
>>>>>>> yibin
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(Article.ARTICLE);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
<<<<<<< HEAD
    public ArticleRecord(UInteger id, String title, Timestamp timeStamp, String content) {
        super(Article.ARTICLE);

        set(0, id);
        set(1, title);
        set(2, timeStamp);
        set(3, content);
=======
    public ArticleRecord(UInteger id, Integer authorId, String title, Timestamp timeStamp, String content) {
        super(Article.ARTICLE);

        set(0, id);
        set(1, authorId);
        set(2, title);
        set(3, timeStamp);
        set(4, content);
>>>>>>> yibin
    }
}
