/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import webdoctor.jooq.tables.DiseaseSymptom;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiseaseSymptomRecord extends TableRecordImpl<DiseaseSymptomRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1373004396;

    /**
     * Setter for <code>webdoctor.disease_symptom.tagid</code>.
     */
    public void setTagid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>webdoctor.disease_symptom.tagid</code>.
     */
    public Integer getTagid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>webdoctor.disease_symptom.diseaseid</code>.
     */
    public void setDiseaseid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>webdoctor.disease_symptom.diseaseid</code>.
     */
    public Integer getDiseaseid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DiseaseSymptom.DISEASE_SYMPTOM.TAGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DiseaseSymptom.DISEASE_SYMPTOM.DISEASEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTagid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDiseaseid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiseaseSymptomRecord value1(Integer value) {
        setTagid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiseaseSymptomRecord value2(Integer value) {
        setDiseaseid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiseaseSymptomRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiseaseSymptomRecord
     */
    public DiseaseSymptomRecord() {
        super(DiseaseSymptom.DISEASE_SYMPTOM);
    }

    /**
     * Create a detached, initialised DiseaseSymptomRecord
     */
    public DiseaseSymptomRecord(Integer tagid, Integer diseaseid) {
        super(DiseaseSymptom.DISEASE_SYMPTOM);

        set(0, tagid);
        set(1, diseaseid);
    }
}
