/**
 * This class is generated by jOOQ
 */
package webdoctor.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import webdoctor.jooq.tables.DiseaseArticle;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiseaseArticleRecord extends TableRecordImpl<DiseaseArticleRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1126619634;

    /**
     * Setter for <code>webdoctor.disease_article.disease_id</code>.
     */
    public void setDiseaseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>webdoctor.disease_article.disease_id</code>.
     */
    public Integer getDiseaseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>webdoctor.disease_article.article_id</code>.
     */
    public void setArticleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>webdoctor.disease_article.article_id</code>.
     */
    public Integer getArticleId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DiseaseArticle.DISEASE_ARTICLE.DISEASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DiseaseArticle.DISEASE_ARTICLE.ARTICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDiseaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiseaseArticleRecord value1(Integer value) {
        setDiseaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiseaseArticleRecord value2(Integer value) {
        setArticleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiseaseArticleRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiseaseArticleRecord
     */
    public DiseaseArticleRecord() {
        super(DiseaseArticle.DISEASE_ARTICLE);
    }

    /**
     * Create a detached, initialised DiseaseArticleRecord
     */
    public DiseaseArticleRecord(Integer diseaseId, Integer articleId) {
        super(DiseaseArticle.DISEASE_ARTICLE);

        set(0, diseaseId);
        set(1, articleId);
    }
}
